# Generated by Django 4.2.dev20221019003145 on 2022-11-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'departments',
                'permissions': (('search_department', 'Can search department'), ('print_department', 'Can print department'), ('export_department', 'Can export department')),
            },
        ),
    ]
