# Generated by Django 4.2.dev20221019003145 on 2022-10-27 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rhoel_unofficial_project', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
