# Generated by Django 4.2.dev20221019003145 on 2022-10-27 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rhoel_unofficial_project', '0003_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='department_id',
            new_name='department',
        ),
    ]
