# Generated by Django 4.2.dev20221019003145 on 2022-11-09 06:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employed_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
